### ISSUE TITLE
ZCAD падает при закрытии чертежа при определенных условиях

### ISSUE THREAD

**Issue by Alligator-1** [zamtmn/zcad#102]
1. Запустить ZCAD и не двигать и не изменять размер его окна!!!
2. Открыть приложенный чертеж и выделить в нём текст
3. Открыть копию этого чертежа(тут не важно, можно и другой чертеж открыть)
4. Закрыть последний открытый чертеж
5. Падение

![zcad_av](https://github.com/zamtmn/zcad/assets/17508903/a7619229-b5f4-4628-a87e-ca0427b18ee8)
[dxf2000_test.zip](https://github.com/zamtmn/zcad/files/14647176/dxf2000_test.zip)

**Comment by Alligator-1** [comment]
[patch102.zip](https://github.com/zamtmn/zcad/files/14657600/patch102.zip)

Этот патч решает падение, но появляется новая проблема в том, что в чекбоксе Dim Style постоянно почти показывает Different

Я не знаю как правильно там логически обработать, может тебе это подскажет куда копать дальше...

**Comment by Alligator-1** [comment]
Исправлено "костылём"
https://github.com/zamtmn/zcad/commit/e0907bebb369f9835fa9cd41dae5fe2a58982302

**Comment by Alligator-1** [comment]
Возможно там же следует обнулять и остальные члены IVars....🤔

**Comment by zamtmn** [comment]
похоже тут надо по другому

**Comment by zamtmn** [comment]
Первый патч почти правильный, у меня там опечатка. в случае отсутствия у текущих выдраных примитивов в ivars.CDimStyle надо присвоить текущий размерный стиль. я скопипастил и непоправил. присвоил размерный стиль в текстовый стиль
