### ISSUE TITLE
Прямоугольник выделения мышью теряет первоначальный вид после закрытия и открытия чертежа

### ISSUE THREAD

**Issue by Alligator-1** [zamtmn/zcad#112]
1. Отрыть приложенный чертеж
2. Повыделять пустое место - прямоугольник красивый синий/зеленый, полупрозрачный, с диагоналями
3. Закрыть чертеж
4. Открыть заново
5. Повыделять пустое место - прямоугольник залит черным, и видны лишь две грани

(на видео цвет нормального прямоугольника не виден, но можно видеть что отрисовываются все его границы и диагонали)
![zcad_bug13](https://github.com/zamtmn/zcad/assets/17508903/ad6c3200-5e6b-4d34-807d-f40f19c69f95)
[dxf2000_test.zip](https://github.com/zamtmn/zcad/files/14662156/dxf2000_test.zip)

**Comment by zamtmn** [comment]
это загадка. сколько не пытался понять почему, так и не понял))

**Comment by Alligator-1** [comment]
> это загадка. сколько не пытался понять почему, так и не понял))

Если не трудно - приложи ссылки на код, где отрисовка этого прямоугольника производится

**Comment by zamtmn** [comment]
https://github.com/zamtmn/zcad/blob/f1f19e06b0f6aed1902ff5ba7ba3a87c076d399f/cad_source/zengine/zgl/drawers/uzglviewareageneral.pas#L425

**Comment by Alligator-1** [comment]
Исправление https://github.com/zamtmn/zcad/commit/8fd5bf4f83215dff9bf73f50ac115df50259ede5
