### ISSUE TITLE
FR: Добавить возможность сбросить настройки вида(окон, положения) на начальные

### ISSUE THREAD

**Issue by Alligator-1** [zamtmn/zcad#119]

**Comment by zamtmn** [comment]
Уже реализовано в "зачаточном" состоянии. найти можно на тулбаре "Layouts" 
![image](https://github.com/zamtmn/zcad/assets/39580611/34b726f7-9841-47b6-a1f2-72b1e837a35f)

**Comment by zamtmn** [comment]
Закрываем?

**Comment by Alligator-1** [comment]
Не проверял, если сбрасывает - то ок

**Comment by zamtmn** [comment]
там смысл не сброс, а переключение между разными настройками. в том числе можно и на начальную откатиться. но если чтото идет не штатно - перезапуск, т.к. проблемы в anchordocking имеются
