### ISSUE TITLE
ZCAD падает при старте (0.9.13.0-0.9.12.0)

### ISSUE THREAD

**Issue by gtfox** [zamtmn/zcad#129]
ZCAD падает при старте (0.9.13.0-0.9.12.0)
0.9.11.0 стартует нормально 32 и 64
Может у меня на нубуке нет какого-нибудь нетфреймворка...

Это так, для информации... на домашнем компуктере у меня всё работает...

![pc](https://github.com/user-attachments/assets/9c607fcb-e8c0-4c92-895d-206d278a358e)
Лог падения
[zcadelectrotech_v0.9.13.0_win64_zcad_windows.log](https://github.com/user-attachments/files/16913061/zcadelectrotech_v0.9.13.0_win64_zcad_windows.log)
Лог нормальной загрузки версии 11
[zcad_electrotech_v0.9.11.0_win32_zcad_windows.log](https://github.com/user-attachments/files/16913062/zcad_electrotech_v0.9.11.0_win32_zcad_windows.log)

**Comment by zamtmn** [comment]
молча падает или создает в %temp% файл zcadcrashreport.txt? его бы тоже приложить

**Comment by gtfox** [comment]
[zcadcrashreport.txt](https://github.com/user-attachments/files/16913169/zcadcrashreport.txt)

**Comment by gtfox** [comment]
![image](https://github.com/user-attachments/assets/f463ee65-b50d-423a-b262-505536215963)

**Comment by zamtmn** [comment]
можно скрин что рядом с ексешником в папке лежит?

**Comment by gtfox** [comment]
![image](https://github.com/user-attachments/assets/af1172ef-8a77-4129-8345-5a9817735238)
![image](https://github.com/user-attachments/assets/971d4d8b-3874-4cab-9909-fc733f635171)

**Comment by zamtmn** [comment]
По какойто причине не может загрузить дллку, это релиз скаченый с гитхаба?
простое решение
![image](https://github.com/user-attachments/assets/ffc206e8-15da-4014-a05f-9a30ad68bad3)
заменить тут false на true, зкад перестанет пытаться юзать внешний фритайп и перейдет на встроенную реализацию парсера ттф

**Comment by gtfox** [comment]
ага, понял, спасибо!
у меня подозрение на шрифт... может он у меня битый какой-нибудь :)
[Desktop.zip](https://github.com/user-attachments/files/16913267/Desktop.zip)

**Comment by zamtmn** [comment]
Нет дело не в шрифте, ругань в момент загрузки длл, до шрифта еще дело не дошло

**Comment by gtfox** [comment]
Заработало! Спасибо! :)

**Comment by Alligator-1** [comment]
ну может кстати и не хватает VCRuntime какого-то
Не откуда эти DLL включаются в дистрибутив, но к примеру в этом источнике:
https://github.com/ubawurinna/freetype-windows-binaries/releases

компилируют с помощью MSVC и пишут, что для работы библиотеки нужно:

`The freetype libraries use the Universal CRT and therefore requires Visual C++ 2015-2022 Redistributable to be present on system.`

**Comment by zamtmn** [comment]
да, надо смотреть чего из зависимостей не хватает

**Comment by gtfox** [comment]
Поставил https://aka.ms/vs/17/release/vc_redist.x64.exe
Вернул RD_UseLazFreeTypeImplementation:=False;
Заработало!

**Comment by gtfox** [comment]
Было очучение, что проблема ушла... но, как всегда, снизу постучали... :)

Клонировал с гитхаба, собрал, запустил (Visual C++ 2015-2022 Redistributable уже установлен)
![Безымянный](https://github.com/user-attachments/assets/628b9665-397b-43c3-a972-db4f21bf8e85)
Установка RD_UseLazFreeTypeImplementation:=True; помогает
[zcad_windows.log](https://github.com/user-attachments/files/16921816/zcad_windows.log)
[zcadcrashreport.txt](https://github.com/user-attachments/files/16921818/zcadcrashreport.txt)

**Comment by zamtmn** [comment]
Попробуй пожалуйста свежую сборку, там обходной путь, падать больше не должно

**Comment by gtfox** [comment]
> Попробуй пожалуйста свежую сборку, там обходной путь, падать больше не должно

Проверил ZCADElectrotech v0.9.14.0-51-ddd75adbc016aeb7419394767b9b06ee9f207223
Не падает при старте

**Comment by zamtmn** [comment]
Хоть это и обход а не решение проблемы, всеравно закрою. Проблема в данном случае не в зкаде, а в не разрешенных зависимостях freetype.dll
