### ISSUE TITLE
Не устанавливаются пакеты

### ISSUE THREAD

**Issue by gtfox** [zamtmn/zcad#131]
Проект собирается
![Безымянный2](https://github.com/user-attachments/assets/fc450d7a-893f-4c96-8b03-6c9ee27822be)
При попытке открыть любую форму просит поставить пакеты
![Безымянный](https://github.com/user-attachments/assets/16b584e1-810c-458b-8523-eb8cc695fb11)
Установка прерывается ошибкой
![Безымянный](https://github.com/user-attachments/assets/4a29a612-d269-40fc-9e89-a2f8a010caa5)

**Comment by Alligator-1** [comment]
Ооооо, chmreader! Как знакомо )
Я много раз сталкивался с этой проблемой, но каждый раз не помню как её решал

Два варианта, даже три:
1. Удалить исходники ZCAD и попробовать заново
если пользуешься git'ом - то удалить всё из рабочей папки, за исключением .git папки и сделать revert всего чтобы откатиться на вариант из репозитория - попробовать снова сделать все процедуры из установки зкада, которые из командной строки производятся
А если гитом не пользуешься - то удалить исходники и скачать заново
2. Удалить Lazarus и установить заново - и опять же снова команды установки зкада и попытка сборки
3. Ну и третий вариант - всё вместе сразу сделать

Эта происходит, на сколько я могу понять из-за конфликта файлов *.ppu или что-то такое, т.к. в ZCAD были включены исходники из RTL FPC и теперь где-то при каких-то условиях происходит конфликт, по хорошему конечно нужно разобраться и научиться стабильно воспроизводить эту проблему - тогда можно с ней поработать и возможно даже получится решить её раз и навсегда(😁)

Если вдруг заметишь какая последовательность действий приводит к такому - желательно задокументировать и отписаться куда-нибудь

**Comment by zamtmn** [comment]
в лазарусе в меню package\Install uninstall packages ...
там удали установленный пакет chmhelppkg

Проблема изза того что зкаду нужен патченый паrет rtl-generics bp из состава fpc. я всё ждал что патчик примут, но надежд всё меньше((

Пока нормального решения нет, только спрятать проблему

**Comment by gtfox** [comment]
Всем спасибо! Удаление пакета помогло!
