### ISSUE TITLE
Наклон в стиле для МТекста не совпадает с наклоном Текста

### ISSUE THREAD

**Issue by gtfox** [zamtmn/zcad#133]
Касаемо текстов:
Создал стиль. Oblique выставил 0,2
![Безымянный2](https://github.com/user-attachments/assets/f9d04763-efa5-4312-b68f-7276b701c30b)
Применил стиль к МТекст - работает!
Применил стиль к Текст - шрифт есть, наклона нет. Вручную выставил наклон 20. Не совпадает с наклоном МТекст-а
Белый - МТекст, Серый - Текст
![Безымянный](https://github.com/user-attachments/assets/33e54d26-4182-4e27-af5f-57e3f3ce470f)

А то, что наклон из стиля не применяется к однострочному тексту - это так и задумано?

**Comment by zamtmn** [comment]
текст и мтекст работают в автокаде по разному. МТекст берет наклон из стиля, у него нет параметра Oblique.
Текст де имеет параметр Oblique, и хранит свой наклон там. из стиля Oblique заполняется только в момент создания текста.

Связано это с тем что текст более старый примитив и был в автокаде с самых первых версий, когда о стилях еще не заморачивались. Такое поведение тянут как обратную совместимость. МТекст появился емнип в 14 автокаде и его поведение более умное

**Comment by gtfox** [comment]
Понял, спасибо! Просто привык в визио, что стили работают на всё. Я вспомнил, что в автокаде последний раз работал до начала САПР-АСУ, а это лет 5 назад :)
