### ISSUE TITLE
Разлет элементов блока 

### ISSUE THREAD

**Issue by vlsx** [zamtmn/zcad#136]
Вновь начали смещаться поля свойств блока при выкидывании блока на чертеж. Данными блоками высоковольтных сетей давно не пользуюсь, но при попытке их использования получается следующее - поля текста свойств  смещаются со своих мест.
![Разлет элементов](https://github.com/user-attachments/assets/96f7f439-9851-4196-9c4d-2e9be6d79102)

https://github.com/user-attachments/assets/4a60ddeb-a0f0-44b5-96cc-d5d7cebb2bdb

[Разлет элементов.zip](https://github.com/user-attachments/files/16987714/default.zip)

**Comment by zamtmn** [comment]
имя блока и в каком файле он определен?

**Comment by vlsx** [comment]
EL_VL_QUESTIONNAIRE2_1 
Просто выбрасываю этот блок на новый лист
