### ISSUE TITLE
Ошибка при одновременном выделении блока и суперлинии

### ISSUE THREAD

**Issue by vlsx** [zamtmn/zcad#138]
https://github.com/user-attachments/assets/90724326-729b-46a6-8cd6-e37d5cbde254

[Ошибка при выделении.zip](https://github.com/user-attachments/files/17001653/default.zip)

**Comment by zamtmn** [comment]
Пролбема в релизном компиляторе 3.2.2 - есть баг с overload функциями в генериках. в транке баг починен, поэтому я проблем не увидел. вроде всё исправил
