### ISSUE TITLE
ZCAD падает при закрытии не сохранённого файла

### ISSUE THREAD

**Issue by gtfox** [zamtmn/zcad#141]
![q1](https://github.com/user-attachments/assets/f62dfa96-3ca8-4d20-8c26-788cb78f21c4)
![Безымянный](https://github.com/user-attachments/assets/7c32dd8b-ea6e-4115-816a-c418504ceb5f)
[zcadcrashreport.txt](https://github.com/user-attachments/files/17215446/zcadcrashreport.txt)
[zcad_windows.log](https://github.com/user-attachments/files/17215448/zcad_windows.log)

Есть еще один момент:
Обычное сохранение, без закрытия, происходит даже в уже существующий файл, не предлагая его перезаписать!

**Comment by zamtmn** [comment]
Вылет вылечил. Добавил диалог выбора имени файла при сохранении нового чертежа (если файла с таким именем нет) что имеется ввиду под

>Обычное сохранение, без закрытия, происходит даже в уже существующий файл, не предлагая его перезаписать!

ведь подразвмевается что этот файл и был открыт и мы его сохраняем

**Comment by gtfox** [comment]
![q1](https://github.com/user-attachments/assets/69bc0ff7-625b-4915-be4d-f57abdd069ef)

Нет запроса на перезапись существующего файла

**Comment by gtfox** [comment]
> Вылет вылечил.

На простых фигурах - да. А если устройства - вылетает

![q1](https://github.com/user-attachments/assets/9d39ffb3-e81d-4542-8811-47c4c276a239)
[zcadcrashreport.txt](https://github.com/user-attachments/files/17234086/zcadcrashreport.txt)
[zcad_windows.log](https://github.com/user-attachments/files/17234090/zcad_windows.log)

**Comment by zamtmn** [comment]
Ты запускаешь зкад по клику на dxf файле на рабочем столе. ты уверен что запускается новая версия? Запускается та, которая ассоциирована с dxf на твоем компе, или файл передается в уже запущенный инстанс зкада. на гифках в заголовке разные версии. при запуске по клитку на диксф этот файл должен открываться и его имя показываться в заголовке. у тебя там "новый файл" я это чинил довольно давно. Чтото идет не так, нужна чистота эксперимента))
С устройствами вылет повторился, разбираюсь. остальное - у меня все ок))

**Comment by gtfox** [comment]
>Чтото идет не так, нужна чистота эксперимента))

ZCAD открываю с exe-шника. На обоих гифках при открытии пустой ZCAD и я, каждый раз, нажимаю кнопку "Новый файл". Версии разные потому, что разница по времени 2 часа и я успел скачать ночную  :)  и уже на ней заснял. 

Остался  запроса на перезапись существующего файла

**Comment by zamtmn** [comment]
Нашел и поправил еще одну проблему при сохранении, но тут уже не всё так просто(( Правля тут могу сломать чтото другое.
С запросом на сохранение понял(( попробую ченить родить)) 
У тебя есть возможность выкладывать не гифки? а например mp4? гифки тут не останавливаются и не мотаются. тяжело смотреть. можно пропустить нужный момент

**Comment by zamtmn** [comment]
Вроде всё поправил

**Comment by gtfox** [comment]
> а например mp4?

ага, хорошо

**Comment by zamtmn** [comment]
Еще раз))

**Comment by zamtmn** [comment]
вроде починено. если что переоткрой
