### ISSUE TITLE
Ошибка при сохранении нового файла

### ISSUE THREAD

**Issue by vlsx** [zamtmn/zcad#144]
Если создать новый файл и сохранить его через команду "Сохранить как", то все сохраняется нормально. Но если выбрать команду "закрыть чертеж" на новом фале с меню "Чертеж такой то не сохранен. сохранить?" - после нажатия "Да" идет вылет программы.

**Comment by zamtmn** [comment]
Ты давно обновлялся? у меня не воспроизводится - я недавно эти механизмы перетряхивал. попробуй на обновленной версии?

**Comment by zamtmn** [comment]
Видимо это починено. если повторится проблема - переоткрой
