### ISSUE TITLE
Printing: bug on blocks

### ISSUE THREAD

**Issue by paolo-caroni** [zamtmn/zcad#17]
If you try to print blocks they simply disappear from the printed paper.
But are drawn on display.

**Comment by zamtmn** [comment]
Can you give an example of a file.dxf with missing blocks?

**Comment by paolo-caroni** [comment]
since I don't own the copyright of the file, I currently can't.
But When I have time I redraw a new file to test the bug and if reappears I will add to /errors.
I have just add 2 file for give you other example of other already known missing stuff.
