### ISSUE TITLE
Cannot render text entity

### ISSUE THREAD

**Issue by zamtmn** [zamtmn/zcad#26]
See  example file. Looks empty, but contain one text entity
[errorwithtext.zip](https://github.com/zamtmn/zcad/files/5620237/errorwithtext.zip)

**Comment by Psycho99** [comment]
I renders pretty nicely on my end.

except for helper box (called system geometry ) that doesn't adjust to get ( around ) rendered text wich make the Horizontal bar of T confused in the box en the last letter a little too close for confort
it's just an adjusting variable to add for capitals in the algorythm that adjust its size .

**Comment by zamtmn** [comment]
Stable or git version? please provide screenshot

**Comment by Psycho99** [comment]
My bad, I'm on 9.8.5

**Comment by zamtmn** [comment]
I have partially correct this error, but not everything depends on me: https://bugs.freepascal.org/view.php?id=38426
