### ISSUE TITLE
TEXT and MTEXT is invisible far from the origin of the coordinate axis

### ISSUE THREAD

**Issue by veb86** [zamtmn/zcad#5]

**Comment by zamtmn** [comment]
![0-02-04-814ff26162f004e71c4f72e799b98232d93585d626929ffde22606a1c566d1d9_9b713367](https://user-images.githubusercontent.com/39580611/41639994-86ac8812-7479-11e8-9b27-c931ecef2449.jpg)

[zpsnew.zip](https://github.com/zamtmn/zcad/files/2118043/zpsnew.zip)

**Comment by zamtmn** [comment]
[zPS-РС-Санпроп.zip](https://github.com/zamtmn/zcad/files/2386418/zPS-.-.zip)
New bug file
