### ISSUE TITLE
Object: Hatching. Incorrect color display

### ISSUE THREAD

**Issue by veb86** [zamtmn/zcad#52]
Объект: Штриховка. Неправильное отображение цвета

**Comment by veb86** [comment]
[GH0052_HatchColor.zip](https://github.com/zamtmn/zcad/files/9828368/GH0052_HatchColor.zip)

**Comment by zamtmn** [comment]
Здесь у примитива задана прозрачность, прозрачность не поддерживается и планов ее поддержки пока нет
