### ISSUE TITLE
Object: Text. Disappears when zooming in/out

### ISSUE THREAD

**Issue by veb86** [zamtmn/zcad#53]
Объект:Текст. При приближении/отдалении исчезает

**Comment by zamtmn** [comment]
Тут использован некий шрифт D431.ttf пожалуйста дай мне его, не могу воспроизвести

**Comment by veb86** [comment]
[D431.zip](https://github.com/zamtmn/zcad/files/9849662/D431.zip)
шрифт D431.ttf

**Comment by zamtmn** [comment]
Проблема в шрифте - контур буквы т имеет самопересечения. Я посмотрю можно ли будет чтото придумать и хоть как-то ее отобразить
![image](https://user-images.githubusercontent.com/39580611/197494846-e540e5eb-21a2-4b79-894e-fd3ff48802b5.png)
