### ISSUE TITLE
Объект: Не работает блок внутри блока

### ISSUE THREAD

**Issue by veb86** [zamtmn/zcad#68]
Проверил что если внутренний блок поместить на чертеж, а верхний блок удалить, то все открывается.
Есть предположение что что то с верхним блоком, его невозможно расчленить

**Comment by veb86** [comment]
[GH0068BlockWithinBlockError.zip](https://github.com/zamtmn/zcad/files/11807767/GH0068BlockWithinBlockError.zip)

**Comment by zamtmn** [comment]
У верхнего блока установлен флаг запрета расчленения. зкад данный флаг не поддерживанет.
Подробней - что не работает, я не понял

**Comment by veb86** [comment]
При попытке открыть файл с таким блоком, zcad падает в ошибку

**Comment by zamtmn** [comment]
Пока закрываем
