### ISSUE TITLE
Ошибка при открытии Autotad файла сохраненным в Zcad

### ISSUE THREAD

**Issue by vlsx** [zamtmn/zcad#73]
При открытии Autocad выдает ошибку
[Uploading ЭМ_СХ_21_.zip…]()

**Comment by zamtmn** [comment]
Файл не приложен((

**Comment by vlsx** [comment]
Зкад версия 0.9.11.00-.151. Открываю в зкаде пустой файл, помещаю любой блок, сохраняю. При попытке открыть автокадом - автокад выдает ошибку.
[Без имени001.dxf.zip](https://github.com/zamtmn/zcad/files/12787286/001.dxf.zip)

**Comment by zamtmn** [comment]
у меня 11.0-164 все работает вроде
открываю приложенный файл вставляю DEVICE_PS_DAT_SMOKE - всё работает

Давай подробный рецепт воспроизведения - имя блока который вставляешь
