### ISSUE TITLE
Не корректное отображение имени стояком

### ISSUE THREAD

**Issue by vlsx** [zamtmn/zcad#78]
На чертеже две пары стояков с разными базовыми менами. У перовой пары "A", у второй "R". В инспекторе базовые и полные имена отображаются верно. Но в фильтре стояков базовые имена отображаются не верно. Из за этого прокладка кабелей методом суперлиний работа не корректно. При чем, если файл был создан в более ранней версии, то имена стояков отображаются в новой версии программы верно. То же самое -  если файл созданный в новой версии пересохранить в старой версии. Проблема возникает только в случае создания и сохранении файла в новой версии.
[Без имени001.zip](https://github.com/zamtmn/zcad/files/13062238/001.zip)
![Снимок](https://github.com/zamtmn/zcad/assets/81608059/abf16305-adec-43c5-834a-33edca25624c)

**Comment by zamtmn** [comment]
![image](https://github.com/zamtmn/zcad/assets/39580611/faa2ebb7-f5c7-45c6-b0a3-5e47bcb38179)

Данные стояки имеют как старые переменные имени `RiserName` так и новые `NMO_Name`. на выноске отображена `NMO_Name`, а в инспекторе используется `RiserName`:
```
SetColumnsCount(3,0);
SetColumnParams(0,'Tree','@@[RiserName]','tmpGUIParamSave_NavRis_C0',1);
SetColumnParams(1,'Elevation','@@[Elevation]','tmpGUIParamSave_NavRis_C1',1);
SetColumnParams(2,'Text','@@[Text]','tmpGUIParamSave_NavRis_C2',1)
```

**Comment by zamtmn** [comment]
я могу выпилить `RiserName` из инспектора, тебе предлагаю вычистить `RiserName` из своих блоков

**Comment by zamtmn** [comment]
Убрал RiserName из настроек инспектора по умолчанию. нужно пересобрать окружение
