### ISSUE TITLE
MTEXT. Inside the dxf file, there is no special character protection (\)

### ISSUE THREAD

**Issue by veb86** [zamtmn/zcad#8]
Specific characters of type (\, {,} ...) should have protection (\)

![2018-06-20_13-57-11](https://user-images.githubusercontent.com/39908908/41654295-abefcdce-7491-11e8-8d36-39014bc17d87.png)
![2018-06-20_13-50-27](https://user-images.githubusercontent.com/39908908/41654060-e07843a6-7490-11e8-8309-c5113986f736.png)
![2018-06-20_13-50-58](https://user-images.githubusercontent.com/39908908/41654061-e1f01204-7490-11e8-8fce-7d7f00b923aa.png)
![2018-06-20_13-55-57](https://user-images.githubusercontent.com/39908908/41654238-772da3d6-7491-11e8-9eda-08f214f40812.png)

**Comment by zamtmn** [comment]
Fixed in 02ae098

**Comment by veb86** [comment]
Almost everything began to work as it should, but there is one problem

ZCAD:
![2018-10-26_15-58-12](https://user-images.githubusercontent.com/39908908/47567773-1c3dac80-d938-11e8-9c74-f427ca944c5d.png)

BRICSCAD:
![2018-10-26_15-58-56](https://user-images.githubusercontent.com/39908908/47567816-32e40380-d938-11e8-9d4a-5c7af0f19b9f.png)

The problem is when the following text is entered "\\P"

**Comment by veb86** [comment]
Template recorded correctly
Content at the end should be as in the template "\\\\P"

**Comment by veb86** [comment]
Add bug file

**Comment by veb86** [comment]
[bug.zip](https://github.com/zamtmn/zcad/files/2792447/bug.zip)

**Comment by zamtmn** [comment]
![fix](https://user-images.githubusercontent.com/39580611/51900622-a124e000-23d7-11e9-8d85-e87388148b50.PNG)
bug.zip mtext content fixed in  2a6292f
