### ISSUE TITLE
Готовые сборки

### ISSUE THREAD

**Issue by prospero78** [zamtmn/zcad#9]
Убедительная просьба: сделайте готовую сборку, или в укажите где скачать. Под шиндошсом работаю, тупой, занятый, не умею. Спасибо, заранее.

**Comment by zamtmn** [comment]
Тут и выкладываю https://github.com/zamtmn/zcad/releases

**Comment by prospero78** [comment]
Блин... Что мешает ссылку в ридми загнать?? (* но спасибо *)

**Comment by zamtmn** [comment]
Ничего не мешает)) добавлю
